/** Rust-core implementation of {@link GitApi}, over Tauri `invoke()` (desktop). */
import {
  tauri_gitGraph,
  tauri_gitCommitDiff,
  tauri_gitCommitFiles,
  tauri_gitListFiles,
  tauri_gitReadFile,
  tauri_gitWriteFile,
  tauri_gitDiff,
  tauri_gitStage,
  tauri_gitUnstage,
  tauri_gitCommit,
  tauri_gitPush,
  tauri_gitPullDefault,
  tauri_gitCreateBranch,
  tauri_gitDeleteBranch,
  tauri_gitBranches,
  tauri_gitSwitchBranch,
  tauri_gitFetch,
  tauri_gitPull,
  tauri_gitMerge,
  tauri_gitRebase,
  tauri_deleteGitRepository,
  tauri_registerGitRepository,
  tauri_cloneGitRepository,
  tauri_selectGitRepository,
  tauri_gitFileSizes,
  tauri_setGitBoard,
  tauri_gitOverview,
  tauri_gitWorktrees,
  tauri_gitCreateWorktree,
  tauri_gitSelectWorktree,
  tauri_gitRemoveWorktree,
  tauri_gitPruneWorktrees,
} from "./tauri-bridge.js";
import type {
  FileSizeRank,
  GitApi,
  GitBranch,
  GitFileContent,
  GitFileStatus,
  GitGraphCommit,
  GitOverview,
} from "./git-api.js";

export const tauriGitApi: GitApi = {
  getGitWorktrees: () => tauri_gitWorktrees() as ReturnType<GitApi["getGitWorktrees"]>,
  createGitWorktree: (options) =>
    tauri_gitCreateWorktree(options) as ReturnType<GitApi["createGitWorktree"]>,
  selectGitWorktree: (path) => tauri_gitSelectWorktree(path),
  removeGitWorktree: (path) => tauri_gitRemoveWorktree(path),
  pruneGitWorktrees: () => tauri_gitPruneWorktrees(),
  getGitGraph: (limit = 200) => tauri_gitGraph(limit) as Promise<GitGraphCommit[]>,
  getGitCommitDiff: (hash, file) => tauri_gitCommitDiff(hash, file),
  getGitCommitFiles: (hash) => tauri_gitCommitFiles(hash) as Promise<GitFileStatus[]>,
  getGitFiles: () => tauri_gitListFiles(),
  getFileSizeRanking: () => tauri_gitFileSizes() as Promise<FileSizeRank[]>,
  getGitFile: (path) => tauri_gitReadFile(path) as Promise<GitFileContent>,
  updateGitFile: (path, content) => tauri_gitWriteFile(path, content),
  getGitDiff: (path, repo) => tauri_gitDiff(path, repo),
  getGitOverview: () => tauri_gitOverview() as Promise<GitOverview>,
  setGitBoard: (names) => tauri_setGitBoard(names),
  gitStage: (paths, repo) => tauri_gitStage(paths, repo),
  gitUnstage: (paths, repo) => tauri_gitUnstage(paths, repo),
  gitCommit: (message, repo) => tauri_gitCommit(message, repo),
  gitPush: (repo) => tauri_gitPush(repo),
  gitPull: (repo) => tauri_gitPull(repo),
  gitMerge: (branch, repo) => tauri_gitMerge(branch, repo),
  gitRebase: (branch, repo) => tauri_gitRebase(branch, repo),
  gitCheckoutDefaultAndPull: () => tauri_gitPullDefault(),
  gitCreateBranch: (name, startPoint, repo) => tauri_gitCreateBranch(name, startPoint, repo),
  gitDeleteBranch: (name, repo) => tauri_gitDeleteBranch(name, repo),
  gitBranches: (repo) => tauri_gitBranches(repo) as Promise<GitBranch[]>,
  gitFetch: (repo) => tauri_gitFetch(repo) as Promise<string>,
  gitSwitchBranch: (name, repo) => tauri_gitSwitchBranch(name, repo),
  deleteGitRepository: (name) => tauri_deleteGitRepository(name),
  selectGitRepository: (name) => tauri_selectGitRepository(name),
  registerGitRepository: async (name, path) => {
    await tauri_registerGitRepository({ name, path });
  },
  cloneGitRepository: (url) => tauri_cloneGitRepository(url),
  adoptGitRepository: () => {
    // The Rust core has no adopt-by-path command yet.
    throw new Error("Adopting a folder as a project is not supported in desktop mode");
  },
  createGitRepository: () => {
    // The Rust core has no create-project command yet.
    throw new Error("Creating a project is not supported in desktop mode");
  },
};
