/** Rust-core implementation of {@link GitApi}, over Tauri `invoke()` (desktop). */
import {
  tauri_gitGraph,
  tauri_gitCommitDiff,
  tauri_gitCommitFiles,
  tauri_gitListFiles,
  tauri_gitReadFile,
  tauri_gitWriteFile,
  tauri_gitDiff,
  tauri_gitStage,
  tauri_gitUnstage,
  tauri_gitCommit,
  tauri_gitPush,
  tauri_gitPullDefault,
  tauri_gitCreateBranch,
  tauri_gitBranches,
  tauri_gitSwitchBranch,
  tauri_gitFetch,
  tauri_deleteGitRepository,
  tauri_registerGitRepository,
  tauri_cloneGitRepository,
  tauri_selectGitRepository,
  tauri_gitFileSizes,
  tauri_setGitBoard,
  tauri_gitOverview,
} from "./tauri-bridge.js";
import type {
  FileSizeRank,
  GitApi,
  GitBranch,
  GitFileContent,
  GitFileStatus,
  GitGraphCommit,
  GitOverview,
} from "./git-api.js";

export const tauriGitApi: GitApi = {
  getGitGraph: (limit = 200) => tauri_gitGraph(limit) as Promise<GitGraphCommit[]>,
  getGitCommitDiff: (hash, file) => tauri_gitCommitDiff(hash, file),
  getGitCommitFiles: (hash) => tauri_gitCommitFiles(hash) as Promise<GitFileStatus[]>,
  getGitFiles: () => tauri_gitListFiles(),
  getFileSizeRanking: () => tauri_gitFileSizes() as Promise<FileSizeRank[]>,
  getGitFile: (path) => tauri_gitReadFile(path) as Promise<GitFileContent>,
  updateGitFile: (path, content) => tauri_gitWriteFile(path, content),
  getGitDiff: (path, repo) => tauri_gitDiff(path, repo),
  getGitOverview: () => tauri_gitOverview() as Promise<GitOverview>,
  setGitBoard: (names) => tauri_setGitBoard(names),
  gitStage: (paths, repo) => tauri_gitStage(paths, repo),
  gitUnstage: (paths, repo) => tauri_gitUnstage(paths, repo),
  gitCommit: (message, repo) => tauri_gitCommit(message, repo),
  gitPush: (repo) => tauri_gitPush(repo),
  gitCheckoutDefaultAndPull: () => tauri_gitPullDefault(),
  gitCreateBranch: (name) => tauri_gitCreateBranch(name),
  gitBranches: (repo) => tauri_gitBranches(repo) as Promise<GitBranch[]>,
  gitFetch: (repo) => tauri_gitFetch(repo) as Promise<string>,
  gitSwitchBranch: (name, repo) => tauri_gitSwitchBranch(name, repo),
  deleteGitRepository: (name) => tauri_deleteGitRepository(name),
  selectGitRepository: (name) => tauri_selectGitRepository(name),
  registerGitRepository: async (name, path) => {
    await tauri_registerGitRepository({ name, path });
  },
  cloneGitRepository: (url) => tauri_cloneGitRepository(url),
};
