/** Agent Environments API entry point shared by browser and desktop. */
import type { AgentEnvApi } from "./agent-env-api.js";
import { httpAgentEnvApi } from "./agent-env-http.js";

const api: AgentEnvApi = httpAgentEnvApi;

export const {
  getAgentEnvAgents,
  getAgentEnvConfigs,
  getAgentEnvDoctor,
  previewAgentEnvChanges,
  applyAgentEnvChanges,
  snapshotAgentEnv,
  getAgentEnvSettings,
  saveAgentEnvSettings,
  setAgentEnvModel,
  listAgentEnvProfiles,
  getAgentEnvProfileRegistryDiff,
  getAgentEnvProfile,
  updateAgentEnvProfile,
  deleteAgentEnvProfile,
  snapshotAgentEnvProfile,
  refreshAgentEnvProfile,
  previewAgentEnvProfileApply,
  applyAgentEnvProfile,
  exportAgentEnvProfile,
  importAgentEnvProfile,
  listAgentEnvRegistryProfiles,
  getRegistryAuthStatus,
  startRegistryAuth,
  getRegistryAuthOutcome,
  registryLogout,
  publishAgentEnvProfile,
  installAgentEnvProfileFromRegistry,
} = api;

export type {
  AgentEnvAgentName,
  AgentEnvApi,
  AgentEnvApplyResult,
  AgentEnvAppliedChange,
  AgentEnvAvailability,
  AgentEnvChangePreview,
  AgentEnvConfig,
  AgentEnvDiffSummary,
  AgentEnvDoctorCheck,
  AgentEnvDoctorResult,
  AgentEnvMcpEntry,
  AgentEnvPendingChange,
  AgentEnvPreviewItem,
  AgentEnvProfile,
  AgentEnvProfileApplyItem,
  AgentEnvProfileApplyPreview,
  AgentEnvProfileApplyResult,
  AgentEnvProfileImportResult,
  AgentEnvProfileRegistryDiff,
  AgentEnvProfileRegistryItemDiff,
  AgentEnvProfileRegistryLinkSummary,
  AgentEnvProfileMcp,
  AgentEnvProfileSummary,
  AgentEnvRegistryInstallResult,
  AgentEnvRegistryProfileSort,
  AgentEnvRegistryProfileSummary,
  AgentEnvRegistryPublishResult,
  AgentEnvRegistryStatus,
  AgentEnvRemoteMcpEntry,
  AgentEnvScope,
  AgentEnvSettings,
  AgentEnvSkill,
  AgentEnvSnapshotResult,
} from "./agent-env-api.js";
