/** Git API entry point shared by browser and desktop. */
import type { GitApi } from "./git-api.js";
import { httpGitApi } from "./git-http.js";

const api: GitApi = httpGitApi;

export const {
  getGitWorktrees,
  createGitWorktree,
  selectGitWorktree,
  removeGitWorktree,
  pruneGitWorktrees,
  getGitGraph,
  getGitCommitDiff,
  getGitCommitFiles,
  getGitFiles,
  searchGitFiles,
  searchGitContent,
  getFileSizeRanking,
  getGitFile,
  updateGitFile,
  getGitDiff,
  getGitOverview,
  setGitBoard,
  gitStage,
  gitUnstage,
  gitCommit,
  getGitIdentity,
  gitPush,
  gitPull,
  gitMerge,
  gitRebase,
  gitCheckoutDefaultAndPull,
  gitCreateBranch,
  gitDeleteBranch,
  gitBranches,
  gitFetch,
  gitSwitchBranch,
  deleteGitRepository,
  selectGitRepository,
  registerGitRepository,
  cloneGitRepository,
  createGitRepository,
  adoptGitRepository,
} = api;

export type {
  GitApi,
  GitFileStatus,
  GitBranch,
  GitGraphRef,
  GitGraphEdge,
  GitGraphCommit,
  GitFileContent,
  FileSizeRank,
  FileNameMatch,
  ContentMatch,
  FileContentMatches,
  ContentSearchResult,
  ContentSearchOptions,
  GitRepoOverview,
  GitOverview,
  GitPushResult,
  GitIdentity,
  GitIdentityState,
  GitCheckoutDefaultAndPullResult,
  GitWorktree,
  GitWorktrees,
} from "./git-api.js";
